# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-03 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(max_length=512)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=128)),
                ('description', models.TextField(max_length=256)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('picture_location', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('confirm_password', models.CharField(max_length=64)),
                ('type', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='comments',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='getServed.Restaurant'),
        ),
    ]
